#include <iostream>
using namespace std;
int main()
{
    // Bitwise operators & -> and , | -> or , ~ -> not , ^ -> Xor
    int a = 4, b = 7;// a= 100 , b = 111 
    // cout << "And :" << (a & b) << endl;
    // cout << "Or :" << (a | b) << endl;
    // cout << "XOr :" << (a ^ b) << endl;
    // cout << "Not a " << ~a << endl;
    // cout << "Not b  " << ~b << endl;

    // // left right operator
    // cout <<"Right shift a "<< (a >> 1) << endl;
    // cout<<" Right shift a " << (a >> 2) << endl;

    // cout<<"Right shift b " << (b >> 1) << endl;
    // cout<<"Right shift b " << (b >> 2) << endl;

    // // left  shift operator
    // cout<<"Left shift a " << (a << 1) << endl;
    // cout<<"Left shift a "  << (a << 2) << endl;

    // cout<<"Left shift b "  << (b << 1) << endl;
    // cout<<"Left shift b "  << (b << 2) << endl;
    
    // Increament Opearator 
    int x = 10 , y = 5  ; 
    int p =0 ,q=0 ; 

cout<<"P value is : "<<p <<endl;
    cout<<"Q value is  : "<<q <<endl;
    // preIncrement 
    cout<<"x value :"<<x<<"\n  y value :"<<y <<endl;
     p = ++x ; 
    q = ++ y ; 
    cout<<"P value is : "<<p <<endl;
    cout<<"Q value is  : "<<q <<endl;
    cout<<"x value :"<<x<<"\n  y value :"<<y <<endl;

    //PostIncreament 
   p =  x++ ; 
    q=  y++ ; 
     cout<<"P value is : "<<p <<endl;
    cout<<"Q value is  : "<<q <<endl;
    cout<<"x value :"<<x<<"\n  y value :"<<y <<endl;

         // Practice some of the question on pre Increment and post Increment and also for Decrement Operator 


         // for loops Concepts 

         

    return 0;
}